import Head from 'next/head';
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css';

export default function Home({ time }) {
	const router = useRouter();

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1>SSR Caching with Next.js</h1>
				<time dateTime={time}>{time}</time>
				<br /> <br />
				<button onClick={() => router.push('/api-caching')}>
					Go to SSG Caching
				</button>
			</main>
		</div>
	);
}

export const getServerSideProps = async ({ req, res }) => {
	res.setHeader(
		'Cache-Control',
		'public, s-maxage=10, stale-while-revalidate=59'
	);
	// the number of seconds specified that determines staleness
	// any response newer than max-age is considered "fresh", and older response is stale

	const time = new Date().toISOString();
	return {
		props: {
			time
		}
	};
};
